import { readFile, writeFile } from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';
import { createOpenAPI } from '../../contracts/dist/index.js';

// zod writes a nullable field as `anyOf: [T, null]`, which some generators skip entirely,
// silently dropping the field. OpenAPI 3.1's `type: [t, 'null']` says the same thing and
// every generator reads it.
const collapseNullableUnions = (node) => {
  if (!node || typeof node !== 'object') return node;
  if (Array.isArray(node)) return node.map(collapseNullableUnions);
  for (const key of Object.keys(node)) node[key] = collapseNullableUnions(node[key]);
  if (!Array.isArray(node.anyOf) || node.anyOf.length !== 2) return node;
  const nullBranch = node.anyOf.find((branch) => branch?.type === 'null');
  const valueBranch = node.anyOf.find((branch) => branch !== nullBranch);
  if (!nullBranch || typeof valueBranch?.type !== 'string') return node;
  const { anyOf, ...rest } = node;
  return { ...rest, ...valueBranch, type: [valueBranch.type, 'null'] };
};

const specification = collapseNullableUnions(createOpenAPI());
const schema = `${JSON.stringify(specification, null, 2)}\n`;
const types = `// Generated by pnpm contracts:generate. Do not edit.\n${astToString(await openapiTS(specification))}`;
const outputs = [
  [new URL('../../contracts/openapi.json', import.meta.url), schema],
  [new URL('../src/generated.ts', import.meta.url), types],
];
for (const [path, contents] of outputs) {
  if (process.argv.includes('--check')) {
    if ((await readFile(path, 'utf8').catch(() => '')) !== contents) {
      console.error(`Contract drift: ${path.pathname}. Run pnpm contracts:generate.`);
      process.exitCode = 1;
    }
  } else await writeFile(path, contents);
}
